project_id = "xkwraysdozypqxygfmqn"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.extract-addresses]
verify_jwt = false
